require('dotenv').config();
const path = require('path');
const { TextInputStyle } = require('discord.js');

/**
 * Configuración general del cliente y sistema de tickets
 */
const clientConfig = {
    token: process.env.DISCORD_TOKEN || '',
    clientId: process.env.CLIENT_ID || '',
    guildId: process.env.GUILD_ID || '',
    logsChannelId: process.env.LOGS_CHANNEL_ID || '',
    staffAlertsChannelId: process.env.STAFF_ALERTS_CHANNEL_ID || '1530125195694706769',
    feedbackChannelId: process.env.FEEDBACK_CHANNEL_ID || '1530125044603424868',
    embedColor: '#990000',
    maxTicketsPerUser: 2,
    maxTicketsPerCategory: 1,
    bannerPath: path.resolve(__dirname, '../../assets/banner.jpg'),
    footerText: 'ARREBATAO RP - Sistema de Tickets',
};

/**
 * Preguntas adaptadas para el modal de cada una de las 11 categorías
 */
const modalFields = {
    soporte: [
        {
            id: 'soporte_nombre_id',
            label: 'Nombre IC e ID',
            placeholder: 'Ej: Juan Perez [1234]',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'soporte_asunto',
            label: 'Asunto o Tipo de Problema',
            placeholder: 'Ej: Problema con inventario / Duda de rol',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'soporte_descripcion',
            label: 'Descripción del problema',
            placeholder: 'Explica detalladamente en qué te podemos ayudar...',
            style: TextInputStyle.Paragraph,
            required: true,
            maxLength: 1000,
        },
        {
            id: 'soporte_pruebas',
            label: 'Pruebas / Enlaces (Opcional)',
            placeholder: 'Links de Imgur, Medal, YouTube, etc.',
            style: TextInputStyle.Paragraph,
            required: false,
            maxLength: 500,
        },
    ],
    reportes: [
        {
            id: 'reportes_nombre_id',
            label: 'Tu Nombre IC e ID',
            placeholder: 'Ej: Carlos Ramos [2345]',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'reportes_reportado',
            label: 'ID / Nombre IC del Reportado',
            placeholder: 'Ej: ID 5678 / Desconocido',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'reportes_normativa',
            label: 'Normativa infringida',
            placeholder: 'Ej: DM, VDM, PG, No valorar vida, etc.',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'reportes_hechos',
            label: 'Relato de los hechos',
            placeholder: 'Explica qué sucedió paso a paso...',
            style: TextInputStyle.Paragraph,
            required: true,
            maxLength: 1000,
        },
        {
            id: 'reportes_pruebas',
            label: 'Enlaces de pruebas en video',
            placeholder: 'Medal, YouTube, Streamable (video claro de la situación)',
            style: TextInputStyle.Paragraph,
            required: true,
            maxLength: 500,
        },
    ],
    apelacion: [
        {
            id: 'apelacion_identificacion',
            label: 'Tu Nombre IC, ID y Discord',
            placeholder: 'Ej: Mateo Gomez [3456] / @usuario',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'apelacion_staff_motivo',
            label: 'Staff sancionador y motivo del ban/warn',
            placeholder: 'Ej: Sancionado por AdminX - Motivo: PG',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'apelacion_fecha',
            label: 'Fecha y duración de la sanción',
            placeholder: 'Ej: 15/09/2026 - Permanente / 7 días',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'apelacion_argumento',
            label: '¿Por qué deberías ser desancionado?',
            placeholder: 'Explica tus motivos, disculpas o malentendidos de forma respetuosa...',
            style: TextInputStyle.Paragraph,
            required: true,
            maxLength: 1000,
        },
        {
            id: 'apelacion_pruebas',
            label: 'Pruebas de descargo (Opcional)',
            placeholder: 'Videos o capturas que respalden tu versión',
            style: TextInputStyle.Paragraph,
            required: false,
            maxLength: 500,
        },
    ],
    donaciones: [
        {
            id: 'donaciones_nombre_id',
            label: 'Nombre IC e ID de juego',
            placeholder: 'Ej: Javier Morales [4567]',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'donaciones_paquete',
            label: 'Paquete o Ítem de Donación',
            placeholder: 'Ej: VIP Platino / Monedas / Vehículo Custom',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'donaciones_metodo',
            label: 'Método de pago utilizado o a usar',
            placeholder: 'Ej: PayPal / Tarjeta / Transferencia / Cripto',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'donaciones_comprobante',
            label: 'Comprobante / ID de Transacción (Opcional)',
            placeholder: 'ID de transacción de PayPal o link del recibo si ya pagaste',
            style: TextInputStyle.Paragraph,
            required: false,
            maxLength: 500,
        },
        {
            id: 'donaciones_dudas',
            label: 'Dudas o detalles adicionales',
            placeholder: 'Cualquier especificación o duda sobre la entrega',
            style: TextInputStyle.Paragraph,
            required: false,
            maxLength: 500,
        },
    ],
    organizaciones: [
        {
            id: 'org_nombre',
            label: 'Nombre de la Organización / Facción',
            placeholder: 'Ej: Cartel del Norte / Los Santos Vagos',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'org_solicitante',
            label: 'Nombre IC y Rango del Solicitante',
            placeholder: 'Ej: Roberto Diaz [Líder / Sublíder] [5678]',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'org_tipo_tramite',
            label: 'Tipo de Trámite',
            placeholder: 'Ej: Creación de Org / Declaración de Guerra / Sede / Alianza',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'org_detalles',
            label: 'Detalles de la solicitud',
            placeholder: 'Explica los puntos clave de tu propuesta o gestión...',
            style: TextInputStyle.Paragraph,
            required: true,
            maxLength: 1000,
        },
        {
            id: 'org_documento',
            label: 'Enlace al documento de la Org / Roster',
            placeholder: 'Link a Google Docs con lore, integrantes y normativas',
            style: TextInputStyle.Paragraph,
            required: false,
            maxLength: 500,
        },
    ],
    reclamos: [
        {
            id: 'reclamos_nombre_id',
            label: 'Nombre IC e ID de juego',
            placeholder: 'Ej: Lucas Silva [6789]',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'reclamos_compra',
            label: 'Producto o compra a reclamar',
            placeholder: 'Ej: Rango VIP / Vehículo exclusivo / Paquete de monedas',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 150,
        },
        {
            id: 'reclamos_transaccion',
            label: 'Método de pago o ID de transacción',
            placeholder: 'Ej: Tebex / PayPal / Tarjeta - ID de transacción',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 150,
        },
        {
            id: 'reclamos_email',
            label: 'Correo de la compra (Opcional)',
            placeholder: 'Ej: correo@gmail.com usado en la tienda de Tebex',
            style: TextInputStyle.Short,
            required: false,
            maxLength: 150,
        },
        {
            id: 'reclamos_detalles',
            label: 'Detalles del problema',
            placeholder: 'Explica qué sucedió. Puedes adjuntar fotos del recibo en el chat del ticket.',
            style: TextInputStyle.Paragraph,
            required: true,
            maxLength: 1000,
        },
    ],
    ck: [
        {
            id: 'ck_tipo',
            label: 'Tipo de CK',
            placeholder: 'Ej: Voluntario / Por Organización / Por Investigación Policial',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'ck_personaje',
            label: 'Nombre IC e ID del personaje',
            placeholder: 'Ej: Marcos Herrera [7890]',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'ck_motivos',
            label: 'Motivos de rol justificados para el CK',
            placeholder: 'Argumenta las razones de peso dentro del rol para la muerte definitiva...',
            style: TextInputStyle.Paragraph,
            required: true,
            maxLength: 1000,
        },
        {
            id: 'ck_antecedentes',
            label: 'Resumen de historia y antecedentes',
            placeholder: 'Breve contexto del personaje y cómo llega a este desenlace...',
            style: TextInputStyle.Paragraph,
            required: true,
            maxLength: 1000,
        },
        {
            id: 'ck_pruebas',
            label: 'Pruebas / Clips de rol acumulados',
            placeholder: 'Enlaces de roles previos que justifiquen el acto',
            style: TextInputStyle.Paragraph,
            required: false,
            maxLength: 500,
        },
    ],
    reportar_staff: [
        {
            id: 'rep_staff_nombre_id',
            label: 'Tu Nombre IC e ID',
            placeholder: 'Ej: Fernando Torres [8901]',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'rep_staff_miembro',
            label: 'Staff reportado (Nombre o Tag)',
            placeholder: 'Ej: StaffName#0000 o Nombre de Discord',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'rep_staff_motivo',
            label: 'Motivo del reporte / Infracción',
            placeholder: 'Ej: Abuso de comandos, trato inadecuado, parcialidad',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'rep_staff_hechos',
            label: 'Relato detallado de lo ocurrido',
            placeholder: 'Explica objetivamente los hechos sucedidos...',
            style: TextInputStyle.Paragraph,
            required: true,
            maxLength: 1000,
        },
        {
            id: 'rep_staff_pruebas',
            label: 'Pruebas irrefutables (Video sin editar)',
            placeholder: 'Medal, YouTube, Streamable con audio y contexto completo',
            style: TextInputStyle.Paragraph,
            required: true,
            maxLength: 500,
        },
    ],
    streamer: [
        {
            id: 'streamer_canal',
            label: 'Plataforma y Nombre de Canal',
            placeholder: 'Ej: Twitch / Kick / YouTube - MiCanalRP',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'streamer_enlace',
            label: 'Enlace directo a tu canal',
            placeholder: 'https://twitch.tv/micanal',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 150,
        },
        {
            id: 'streamer_estadisticas',
            label: 'Media de espectadores y seguidores',
            placeholder: 'Ej: 25 viewers de media, 1500 seguidores',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'streamer_horarios',
            label: 'Horarios de transmisión en ARREBATAO RP',
            placeholder: 'Ej: Lunes a Viernes 20:00 - 00:00 (Hora Servidor)',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'streamer_propuesta',
            label: '¿Qué contenido aportarás a la ciudad?',
            placeholder: 'Planes de rol, facción a la que perteneces o proyectos en stream...',
            style: TextInputStyle.Paragraph,
            required: false,
            maxLength: 500,
        },
    ],
    negocios: [
        {
            id: 'negocios_nombre_contacto',
            label: 'Nombre IC, ID y Teléfono',
            placeholder: 'Ej: Sebastian Ruiz [9012] - Tel: 555-0199',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'negocios_empresa',
            label: 'Nombre del Negocio o Empresa',
            placeholder: 'Ej: Taller Mecánico Ruiz / Club Nocturno Bahama',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'negocios_tipo_ubicacion',
            label: 'Giro del negocio y ubicación deseada',
            placeholder: 'Ej: Concesionario de lujo / Vinewood',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'negocios_propuesta',
            label: 'Plan de negocio y dinámicas de rol',
            placeholder: 'Explica qué actividades y empleos generará tu negocio para la ciudad...',
            style: TextInputStyle.Paragraph,
            required: true,
            maxLength: 1000,
        },
        {
            id: 'negocios_documento',
            label: 'Catálogo / Dossier (Opcional)',
            placeholder: 'Enlace a dossier de presentación en Google Docs o Drive',
            style: TextInputStyle.Paragraph,
            required: false,
            maxLength: 500,
        },
    ],
    postulaciones: [
        {
            id: 'postulaciones_ooc',
            label: 'Nombre real y Edad (OOC)',
            placeholder: 'Ej: Daniel, 21 años',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'postulaciones_ic',
            label: 'Nombre IC y tiempo en ARREBATAO RP',
            placeholder: 'Ej: Daniel Ramos [1011] - 6 meses en la ciudad',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'postulaciones_puesto',
            label: 'Puesto o Facción a postularse',
            placeholder: 'Ej: Staff de Soporte / Moderador / EMS / LSPD',
            style: TextInputStyle.Short,
            required: true,
            maxLength: 100,
        },
        {
            id: 'postulaciones_experiencia',
            label: 'Experiencia previa en roles similares',
            placeholder: 'Detalla servidores y cargos que hayas desempeñado anteriormente...',
            style: TextInputStyle.Paragraph,
            required: true,
            maxLength: 1000,
        },
        {
            id: 'postulaciones_disponibilidad',
            label: 'Disponibilidad horaria y aportación',
            placeholder: 'Horas disponibles al día y qué aportarías al equipo...',
            style: TextInputStyle.Paragraph,
            required: true,
            maxLength: 1000,
        },
    ],
};

/**
 * Mapeo completo de las 11 categorías de tickets
 */
const categories = {
    soporte: {
        id: 'soporte',
        name: 'Soporte',
        emoji: null, // Puedes colocar un emoji personalizado aquí más adelante, ej: '<:soporte:123456789>'
        categoryId: '1530124703606509668',
        staffRoles: ['1530124436059983922'],
        higherRolesAllowed: false,
        ticketPrefix: 'soporte',
        description: 'Dudas técnicas, problemas o atención al cliente.',
        modalTitle: 'Ticket de Soporte',
        modalFields: modalFields.soporte,
    },
    reportes: {
        id: 'reportes',
        name: 'Reportes',
        emoji: null, // Puedes colocar un emoji personalizado aquí más adelante, ej: '<:reportes:123456789>'
        categoryId: '1530124706169094195',
        staffRoles: ['1530124436059983922'],
        higherRolesAllowed: false,
        ticketPrefix: 'reporte',
        description: 'Reporte de usuarios por infringir normativas.',
        modalTitle: 'Reporte a Jugador',
        modalFields: modalFields.reportes,
    },
    apelacion: {
        id: 'apelacion',
        name: 'Apelación',
        emoji: null, // Puedes colocar un emoji personalizado aquí más adelante, ej: '<:apelacion:123456789>'
        categoryId: '1530124708605853786',
        staffRoles: ['1542655847547666612'],
        higherRolesAllowed: false,
        ticketPrefix: 'apelacion',
        description: 'Apelación de sanciones o baneos.',
        modalTitle: 'Apelación de Sanción',
        modalFields: modalFields.apelacion,
    },
    donaciones: {
        id: 'donaciones',
        name: 'Donaciones',
        emoji: null, // Puedes colocar un emoji personalizado aquí más adelante, ej: '<:donaciones:123456789>'
        categoryId: '1530124710820577421',
        staffRoles: ['1530124417244598312'],
        higherRolesAllowed: true,
        ticketPrefix: 'donacion',
        description: 'Compras, donaciones o información de la tienda.',
        modalTitle: 'Donaciones y Tienda',
        modalFields: modalFields.donaciones,
    },
    organizaciones: {
        id: 'organizaciones',
        name: 'Organizaciones',
        emoji: null, // Puedes colocar un emoji personalizado aquí más adelante, ej: '<:organizaciones:123456789>'
        categoryId: '1530124713316188170',
        staffRoles: [
            '1530124443664253138',
            '1530124441928077312',
            '1530124440199757934'
        ],
        higherRolesAllowed: false,
        ticketPrefix: 'org',
        description: 'Creación o gestión de facciones y organizaciones.',
        modalTitle: 'Gestión de Organización',
        modalFields: modalFields.organizaciones,
    },
    reclamos: {
        id: 'reclamos',
        name: 'Reclamos',
        emoji: null, // Puedes colocar un emoji personalizado aquí más adelante, ej: '<:reclamos:123456789>'
        categoryId: '1530124715652288633',
        staffRoles: ['1530124417244598312'],
        higherRolesAllowed: false,
        ticketPrefix: 'reclamo',
        description: 'Reclamos sobre compras de la tienda, rangos y paquetes.',
        modalTitle: 'Reclamo de Compras',
        modalFields: modalFields.reclamos,
    },
    ck: {
        id: 'ck',
        name: 'Ck - Pkt',
        emoji: null, // Puedes colocar un emoji personalizado aquí más adelante, ej: '<:ck:123456789>'
        categoryId: '1530124718567325766',
        staffRoles: [
            '1530124427885543554',
            '1549085104876421212',
            '1542655847547666612'
        ],
        higherRolesAllowed: false,
        ticketPrefix: 'ck',
        description: 'Solicitud o reporte de muerte permanente.',
        modalTitle: 'Solicitud de Ck - Pkt',
        modalFields: modalFields.ck,
    },
    reportar_staff: {
        id: 'reportar_staff',
        name: 'Reportar Staff',
        emoji: null, // Puedes colocar un emoji personalizado aquí más adelante, ej: '<:reportar_staff:123456789>'
        categoryId: '1530124721516183632',
        staffRoles: ['1530124423397380166'],
        higherRolesAllowed: false,
        ticketPrefix: 'rep-staff',
        description: 'Reportes que debe revisar la directiva sobre el staff.',
        modalTitle: 'Reporte a Miembro del Staff',
        modalFields: modalFields.reportar_staff,
    },
    streamer: {
        id: 'streamer',
        name: 'Streamer',
        emoji: null, // Puedes colocar un emoji personalizado aquí más adelante, ej: '<:streamer:123456789>'
        categoryId: '1530124723898286202',
        staffRoles: ['1548133950814290010'],
        higherRolesAllowed: false,
        ticketPrefix: 'streamer',
        description: 'Solicitud del rol y beneficios de creador de contenido.',
        modalTitle: 'Postulación a Rango Streamer',
        modalFields: modalFields.streamer,
    },
    negocios: {
        id: 'negocios',
        name: 'Negocios',
        emoji: null, // Puedes colocar un emoji personalizado aquí más adelante, ej: '<:negocios:123456789>'
        categoryId: '1530978495658852353',
        staffRoles: ['1530124413687566437'],
        higherRolesAllowed: false,
        ticketPrefix: 'negocio',
        description: 'Propuestas de negocios dentro del roleplay.',
        modalTitle: 'Gestión de Negocio o Empresa',
        modalFields: modalFields.negocios,
    },
    postulaciones: {
        id: 'postulaciones',
        name: 'Postulaciones',
        emoji: null, // Puedes colocar un emoji personalizado aquí más adelante, ej: '<:postulaciones:123456789>'
        categoryId: '1545513352472559766',
        staffRoles: ['1545513352472559766'],
        higherRolesAllowed: false,
        ticketPrefix: 'postulacion',
        description: 'Postulación para el equipo de staff.',
        modalTitle: 'Postulación a Staff',
        modalFields: modalFields.postulaciones,
    },
};

/**
 * Botones rápidos en el panel principal (las 4 categorías más solicitadas)
 */
const quickButtons = ['soporte', 'reportes', 'donaciones', 'reclamos'];

module.exports = {
    clientConfig,
    categories,
    quickButtons,
    modalFields,
};
